FROM quay.io/openshiftio/rhel-base-python3:latest

LABEL maintainer="Avishkar Gupta <avgupta@redhat.com>"

COPY ./insights_engine /insights_engine
COPY ./requirements.txt /requirements.txt

RUN chmod 0777 /insights_engine/scripts/entrypoint.sh

RUN pip3 install -r requirements.txt

ENTRYPOINT ["/insights_engines/scripts/entrypoint.sh"]
